name = "wee_noise_maker_samd51"
description = "Shiny new project"
version = "0.0.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["wee_noise_maker_samd51"]

[gpr-set-externals]
BBQUEUE_WORD_SIZE="32"

[[depends-on]]  # This line was added by `alr with`
hal = "*"  # This line was added by `alr with`

[[depends-on]]  # This line was added by `alr with`
bbqueue = "*"  # This line was added by `alr with`

[[depends-on]]  # This line was added by `alr with`
littlefs = "*"  # This line was added by `alr with`

[[depends-on]]  # This line was added by `alr with`
cortex_m = "*"  # This line was added by `alr with`

[[depends-on]]  # This line was added by `alr with`
samd51_hal = "*"  # This line was added by `alr with`

[[depends-on]]  # This line was added by `alr with`
virtapu = "*"  # This line was added by `alr with`

[[depends-on]]  # This line was added by `alr with`
usb_embedded = "*"  # This line was added by `alr with`

[[depends-on]]  # This line was added by `alr with`
embedded_components = "*"  # This line was added by `alr with`
